
INSERT INTO disciplin (Navn, Resultattype) VALUES
                                               ('1-milløb (atletik)', 'sek'),
                                               ('10.000-meterløb (atletik)', 'sek'),
                                               ('100-meterløb (atletik)', 'sek'),
                                               ('110 meter hækkeløb', 'sek'),
                                               ('1500-meterløb (atletik)', 'sek'),
                                               ('200 meter hækkeløb', 'sek'),
                                               ('200-meterløb (atletik)', 'sek'),
                                               ('3000-meterløb (atletik)', 'sek'),
                                               ('4 × 100-meterløb (atletik)', 'sek'),
                                               ('4 × 400-meterløb (atletik)', 'sek'),
                                               ('400 meter hækkeløb', 'sek'),
                                               ('400-meterløb (atletik)', 'sek'),
                                               ('4x400-meterløb blandet hold (atletik)', 'sek'),
                                               ('5000-meter-løb (atletik)', 'sek'),
                                               ('60 meter hækkeløb', 'sek'),
                                               ('60-meterløb (atletik)', 'sek'),
                                               ('800-meterløb (atletik)', 'sek'),
                                               ('Cross (løbesport)', 'sek'),
                                               ('Diskoskast (atletik)', 'cm'),
                                               ('Femkamp (atletik)', 'sek'),
                                               ('Forhindringsløb (atletik)', 'sek'),
                                               ('Halvmaratonløb (løbesport)', 'sek'),
                                               ('Hammerkast (atletik)', 'cm'),
                                               ('Højdespring (atletik)', 'cm'),
                                               ('Højdespring uden tilløb (atletik)', 'cm'),
                                               ('Kastefemkamp (atletik)', 'cm'),
                                               ('Kastetrekamp', 'cm'),
                                               ('Kuglestød (atletik)', 'cm'),
                                               ('Kørestolsrace', 'sek'),
                                               ('Længdespring (atletik)', 'cm'),
                                               ('Længdespring uden tilløb (atletik)', 'cm'),
                                               ('Maratonløb (løbesport)', 'sek'),
                                               ('Slyngboldkast (atletik)', 'cm'),
                                               ('Spydkast (atletik)', 'cm'),
                                               ('Stangspring (atletik)', 'cm'),
                                               ('Syvkamp (atletik)', 'sek'),
                                               ('Tikamp (atletik)', 'sek'),
                                               ('Tovtrækning', 'sek'),
                                               ('Trail (løbesport)', 'sek'),
                                               ('Trespring (atletik)', 'cm'),
                                               ('Trespring uden tilløb (atletik)', 'cm'),
                                               ('Vægtkast (atletik)', 'cm');

INSERT INTO deltager (Navn, Gender, Alder, Klub) VALUES
                                                     ('John Doe', 'Male', 25, 'Athletic Club A'),
                                                     ('Jane Smith', 'Female', 30, 'Running Club B'),
                                                     ('Michael Johnson', 'Male', 28, 'Soccer Club C'),
                                                     ('Emily Brown', 'Female', 22, 'Swimming Club D'),
                                                     ('David Lee', 'Male', 26, 'Basketball Club E'),
                                                     ('Sarah Wilson', 'Female', 29, 'Tennis Club F'),
                                                     ('Chris Taylor', 'Male', 27, 'Cycling Club G'),
                                                     ('Jessica Green', 'Female', 24, 'Gymnastics Club H'),
                                                     ('Daniel White', 'Male', 31, 'Hiking Club I'),
                                                     ('Olivia Clark', 'Female', 23, 'Volleyball Club J'),
                                                     ('Matthew Martinez', 'Male', 32, 'Chess Club K'),
                                                     ('Sophia Rodriguez', 'Female', 26, 'Badminton Club L'),
                                                     ('James Thomas', 'Male', 29, 'Track Club M'),
                                                     ('Ella Hernandez', 'Female', 28, 'Rowing Club N'),
                                                     ('Benjamin Moore', 'Male', 27, 'Boxing Club O'),
                                                     ('Mia King', 'Female', 25, 'Karate Club P'),
                                                     ('William Young', 'Male', 30, 'Fencing Club Q'),
                                                     ('Amelia Hill', 'Female', 31, 'Archery Club R'),
                                                     ('Alexander Scott', 'Male', 24, 'Wrestling Club S'),
                                                     ('Chloe Hall', 'Female', 22, 'Golf Club T');


INSERT INTO deltager_disciplin (deltager_id, disciplin_id)
VALUES
    (1, 1),
    (1, 2),
    (2, 4),
    (3, 2),
    (3, 3),
    (4, 3),
    (5, 1),
    (5, 5);

INSERT INTO resultat (DeltagerID, DisciplinID, Dato, Resultatværdi) VALUES
                                                                        (1, 1, '2023-01-05', '10.5 sek'),
                                                                        (1, 2, '2023-01-06', '180 cm'),
                                                                        (1, 3, '2023-01-07', '25.2 sek'),
                                                                        (1, 4, '2023-01-08', '9.8 m'),
                                                                        (1, 5, '2023-01-09', '15.5 sek'),
                                                                        (2, 2, '2023-01-05', '175 cm'),
                                                                        (2, 3, '2023-01-06', '24.8 sek'),
                                                                        (2, 6, '2023-01-07', '8.5 m'),
                                                                        (2, 8, '2023-01-08', '5 rounds'),
                                                                        (2, 10, '2023-01-09', '12 points'),
                                                                        (3, 1, '2023-01-05', '10.7 sek'),
                                                                        (3, 4, '2023-01-06', '9.5 m'),
                                                                        (3, 5, '2023-01-07', '16.2 sek'),
                                                                        (3, 7, '2023-01-08', '22 hits'),
                                                                        (3, 9, '2023-01-09', '36 points'),
                                                                        (4, 3, '2023-01-05', '23.5 sek'),
                                                                        (4, 5, '2023-01-06', '17.2 sek'),
                                                                        (4, 6, '2023-01-07', '190 cm'),
                                                                        (4, 7, '2023-01-08', '18 hits'),
                                                                        (4, 10, '2023-01-09', '9 points'),
                                                                        (5, 1, '2023-01-05', '10.9 sek'),
                                                                        (5, 2, '2023-01-06', '185 cm'),
                                                                        (5, 4, '2023-01-07', '9.7 m'),
                                                                        (5, 7, '2023-01-08', '21 hits'),
                                                                        (5, 8, '2023-01-09', '6 rounds'),
                                                                        (6, 2, '2023-01-05', '178 cm'),
                                                                        (6, 3, '2023-01-06', '24.5 sek'),
                                                                        (6, 5, '2023-01-07', '16.5 sek'),
                                                                        (6, 6, '2023-01-08', '185 cm'),
                                                                        (6, 9, '2023-01-09', '32 points'),
                                                                        (7, 1, '2023-01-05', '11.1 sek'),
                                                                        (7, 4, '2023-01-06', '9.2 m'),
                                                                        (7, 7, '2023-01-07', '19 hits'),
                                                                        (7, 8, '2023-01-08', '7 rounds'),
                                                                        (7, 10, '2023-01-09', '14 points'),
                                                                        (8, 3, '2023-01-05', '23.9 sek'),
                                                                        (8, 5, '2023-01-06', '18.2 sek'),
                                                                        (8, 6, '2023-01-07', '188 cm'),
                                                                        (8, 9, '2023-01-08', '30 points'),
                                                                        (8, 10, '2023-01-09', '10 points'),
                                                                        (9, 1, '2023-01-05', '11.3 sek'),
                                                                        (9, 2, '2023-01-06', '182 cm'),
                                                                        (9, 3, '2023-01-07', '24.2 sek'),
                                                                        (9, 4, '2023-01-08', '9.0 m'),
                                                                        (9, 5, '2023-01-09', '11.8 sek'),
                                                                        (10, 2, '2023-01-05', '177 cm');


